#!/usr/bin/env zsh

git config --global init.defaultBranch mainline
git config --global --add safe.directory .(:A)

# Discover all the tests. I think this helps VS Code find them and show the UI run test buttons in the margin
pytest --collect-only

